#!/usr/bin/env bash
# A script that configures a new Ubuntu machine:
#   Install nginx on your web-01 server
#   Nginx should be listening on port 80
#   When querying Nginx at its root '/' with a GET request using curl,
#       it must return a page that contains the string Holberton School
#   Can’t use systemctl for restarting nginx

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.html
sudo service nginx restart
