#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page
#   that contains the string Ceci n'est pas une page.
# The page must return an HTTP 404 error code.

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.html
line="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "35i $line" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
lines="\\\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}"
sudo sed -i "36i $lines" /etc/nginx/sites-enabled/default
sudo service nginx restart
