#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page
#   that contains the string Ceci n'est pas une page.
# The page must return an HTTP 404 error code.

echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
lines="\\\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}"
sudo sed -i "36i $lines" /etc/nginx/sites-enabled/default
sudo service nginx restart
