#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header
#   The name of the custom HTTP header must be X-Served-By
#   The value of the custom HTTP header must be the hostname of the server
#       Nginx is running on

sudo apt-get -y update
sudo apt-get -y install nginx
line="24i\\\tadd_header X-Served-By \$hostname;"
sudo sed -i "${line}" /etc/nginx/sites-enabled/default
sudo service nginx restart
