#!/usr/bin/env bash
# A script that configures a server to fit the requirements:
#   nginx must be running as 'nginx' user
#   nginx must be listening on all active IPs on port 8080
chmod 700 /etc/nginx/nginx.config
chown nginx:nginx /etc/nginx/nginx.config
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
