#!/usr/bin/env bash
# Sets NGINX to run as the nginx user
pkill apache
chmod 700 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
